<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>LOKWODVisitorKey</AssemblyName>
    <RootNamespace>LOKWOD.VisitorKey</RootNamespace>
    <Version>1.0.5</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(ProgramFiles)\IO Center\hidapi.dll" Link="hidapi.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('$(ProgramFiles)\IO Center\hidapi.dll')" />
  </ItemGroup>
</Project>
